# Generated by Django 4.2.7 on 2023-11-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_pedido_data_alter_pedido_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
    ]
